baseURL = "https://JATAYU000.github.io/jatayu.github.io/"
languageCode = "en-us"
title = "SHRIVATHS S NAIR"
theme = "hugo-ink"
paginate = 5

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "Crisp, minimal personal Blog "

	# Optional 64x64 avatar image.
	avatar = "https://img.freepik.com/free-vector/mysterious-mafia-man-smoking-cigarette_52683-34828.jpg?size=626&ext=jpg&ga=GA1.2.370414137.1694356346&semt=sph"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/JATAYU000"

#[[params.social]]
#name = "RSS"
#icon = "rss"
#url = "/index.xml"

[taxonomies]
   tag = "tags"
